# arxivの学問領域の指定
subject: 'cat:cond-mat.mtrl-sci* OR cat:cs.AI'

# 検索キーワード
keywords:
        adhesive: 3
        energy release rate: 3
        creep: 3
        bonding joint: 2
        fracture toughness: 2
        epoxy: 2
        dcb: 1
        double cantilever beam: 1
        crack growth rate: 3
        water: 1
        moisture: 1
        AI: 3
        neural network: 3

# 通知の閾値
score_threshold: 0
